const PostActionTypes = {
    FETCH_POSTS_START: 'FETCH_POSTS_START',
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
    FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',
    FETCH_USER_POSTS_START: 'FETCH_USER_POSTS_START',
    FETCH_USER_POSTS_SUCCESS: 'FETCH_USER_POSTS_SUCCESS',
    FETCH_USER_POSTS_FAILURE: 'FETCH_USER_POSTS_FAILURE',
    SUBMIT_POST_START: 'SUBMIT_POST_START',
    SUBMIT_POST_SUCCESS: 'SUBMIT_POST_SUCCESS',
    SUBMIT_POST_FAILURE: 'SUBMIT_POST_FAILURE',
    CHANGE_SORT: 'CHANGE_SORT',
    SUBMIT_REPLY_TO_POST_SUCCESS:'SUBMIT_REPLY_TO_POST_SUCCESS',
    FETCH_LIKES_FAILURE: 'FETCH_LIKES_FAILURE',
    FETCH_REPLIES_FAILURE: 'FETCH_REPLIES_FAILURE',
    SUBMIT_LIKE_START:'SUBMIT_LIKE_START',
    SUBMIT_LIKE_SUCCESS: 'SUBMIT_LIKE_SUCCESS',
    SUBMIT_LIKE_FAILURE: 'SUBMIT_LIKE_FAILURE',
    DELETE_LIKE_START:'DELETE_LIKE_START',
    DELETE_LIKE_SUCCESS: 'DELETE_LIKE_SUCCESS',
    DELETE_LIKE_FAILURE: 'DELETE_LIKE_FAILURE'
}
export default PostActionTypes;