export const ReplyActionTypes = {
    TOGGLE_REPLY_FROM_HIDDEN:'TOGGLE_REPLY_FROM_HIDDEN',
    SUBMIT_REPLY_TO_POST_START:'SUBMIT_REPLY_TO_POST_START',
    SUBMIT_REPLY_TO_POST_FAIL:'SUBMIT_REPLY_TO_POST_FAIL'
};